### ISSUE TITLE
DAC8560

### ISSUE THREAD

**Issue by Pilgrim182551** [RobTillaart/DAC8551#22]
Would it be possible to extend the library with a DAC8560?

**Comment by RobTillaart** [comment]
Thanks for your question,

Don't know if it is possible, it they are look-alikes with small differences, it is probably relative easy.
Otherwise it is better to make a dedicated library (copy past strip re-implement etc).

Need to have a look at the datasheet to decide what would be better way.  At the moment I have a dozen open issues, and I'm rather busy, so it might take a few days before I dive into the details.

**Comment by RobTillaart** [comment]
Had a quick look at the datasheet, the 8560 has more functionality, the "Data Input Register Format" looks similar.

Have you tried this DAC8551 to drive the DAC8560?
if so did it work or not or ???

**Comment by Pilgrim182551** [comment]
No problem, I understand... Thank you!

Dne so 26. říj 2024 16:50 uživatel Rob Tillaart ***@***.***>
napsal:

**Comment by RobTillaart** [comment]
@Pilgrim182551 

To be continued here: https://github.com/RobTillaart/DAC8560/issues/2

**Comment by Pilgrim182551** [comment]
> Had a quick look at the datasheet, the 8560 has more functionality, the "Data Input Register Format" looks similar.
> 
> Have you tried this DAC8551 to drive the DAC8560? if so did it work or not or ???

Have been waiting for PCBs, they are to come next week, will let you know...

**Comment by RobTillaart** [comment]
Thanks for the update,
Please use the other issue to report when the PCB arrives.
